name: matomo_forever
description: A perennial Dart plugin to send data to a Matomo server with a Flutter example app.
version: 1.0.4+1
homepage: https://github.com/lcuis/matomo_forever

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: li.jod.matomo_forever
        pluginClass: MatomoForeverPlugin
      ios:
        pluginClass: MatomoForeverPlugin
      macos:
        pluginClass: MatomoForeverPlugin
        default_package: matomo_forever
      linux:
        pluginClass: MatomoForeverPlugin
        default_package: matomo_forever
      windows:
        pluginClass: MatomoForeverPlugin
        default_package: matomo_forever
      web:
        pluginClass: MatomoForeverPlugin
        fileName: matomo_forever.dart
        default_package: matomo_forever